// <auto-generated />
using System;
using LoginAppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoginAppData.Migrations
{
    [DbContext(typeof(LoginDataContext))]
    [Migration("20230505074605_newLTDataBase")]
    partial class newLTDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("LoginAppData.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccountType")
                        .HasColumnType("boolean")
                        .HasColumnName("account_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("Password")
                        .HasColumnType("bigint")
                        .HasColumnName("password");

                    b.Property<string>("SafteyWord")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("safety_word");

                    b.HasKey("Id");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("LoginAppData.ToDoItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ListId")
                        .HasColumnType("integer");

                    b.Property<string>("Task")
                        .HasColumnType("text")
                        .HasColumnName("task");

                    b.HasKey("ItemId");

                    b.HasIndex("ListId");

                    b.ToTable("todoitems");
                });

            modelBuilder.Entity("LoginAppData.ToDoListModel", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ListId"));

                    b.Property<string>("ListName")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ListId");

                    b.ToTable("todolist");
                });

            modelBuilder.Entity("LoginAppData.ToDoItem", b =>
                {
                    b.HasOne("LoginAppData.ToDoListModel", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("LoginAppData.ToDoListModel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
